# Generated by Django 2.2.4 on 2019-12-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20191210_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pubhouse',
        ),
        migrations.AddField(
            model_name='pubhouse',
            name='books',
            field=models.ManyToManyField(blank=True, to='p_library.Book', verbose_name='Книги'),
        ),
    ]
