# Generated by Django 2.2.4 on 2019-12-10 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_auto_20191210_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubhouse',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='pubhouse',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='p_library.PubHouse', verbose_name='Издательство'),
        ),
    ]
