# Generated by Django 3.0.2 on 2020-02-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0014_auto_20200201_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreader',
            name='comment',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Комментарий'),
        ),
    ]
